import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.slice(2).includes("--check");

const sha256 = (value) => createHash("sha256").update(value).digest("hex");
const readText = (relative) => readFile(resolveInside(relative), "utf8");
const readJson = async (relative) => JSON.parse(await readText(relative));

function resolveInside(relative) {
  const absolute = resolve(root, relative);
  if (absolute !== root && !absolute.startsWith(root + sep)) {
    throw new Error(`path escapes repository root: ${relative}`);
  }
  return absolute;
}

function sortedUnique(values) {
  return [...new Set(values)].sort();
}

function extract(sql, expression) {
  return sortedUnique([...sql.matchAll(expression)].map((match) => match[1].toLowerCase()));
}

async function writeOrCheck(relative, content) {
  const absolute = resolveInside(relative);
  if (checkOnly) {
    const actual = await readFile(absolute, "utf8").catch(() => "");
    if (actual !== content) throw new Error(`${relative} is stale; run node tools/materialize-desired.mjs`);
    return;
  }
  await writeFile(absolute, content);
}

const sourcesText = await readText("contracts/database/sources.json");
const sources = JSON.parse(sourcesText);
const schemaText = await readText("contracts/database/schema.json");
const schema = JSON.parse(schemaText);
const chunks = [];

for (const source of sources.sources) {
  if (!source.path.startsWith("migrations/declarative/")) {
    throw new Error(`canonical source must live under migrations/declarative: ${source.path}`);
  }
  const sql = await readText(source.path);
  const digest = sha256(sql);
  if (digest !== source.sha256) {
    throw new Error(`source digest mismatch for ${source.path}: expected ${source.sha256}, got ${digest}`);
  }
  chunks.push(`-- BEGIN canonical source: ${source.path}\n${sql.trimEnd()}\n-- END canonical source: ${source.path}\n`);
}

const desired = [
  "-- Generated by tools/materialize-desired.mjs. DO NOT EDIT.",
  "-- Inputs and immutable upstream provenance are declared in contracts/database/sources.json.",
  "",
  ...chunks,
].join("\n");

const inventory = schema["x-lib-core"];
const actualTables = extract(desired, /create\s+table\s+if\s+not\s+exists\s+([a-z_][a-z0-9_]*)/gi);
const actualFunctions = extract(desired, /create\s+or\s+replace\s+function\s+([a-z_][a-z0-9_]*)/gi);
const expectedTables = sortedUnique(inventory.tables);
const expectedFunctions = sortedUnique(inventory.functions);

if (JSON.stringify(actualTables) !== JSON.stringify(expectedTables)) {
  throw new Error(`table inventory drift: expected ${expectedTables.join(", ")}, got ${actualTables.join(", ")}`);
}
if (JSON.stringify(actualFunctions) !== JSON.stringify(expectedFunctions)) {
  throw new Error(`function inventory drift: expected ${expectedFunctions.join(", ")}, got ${actualFunctions.join(", ")}`);
}

const provenance = JSON.stringify({
  format: 1,
  canonicalRepository: sources.canonicalRepository,
  sourceManifestSha256: sha256(sourcesText),
  persistenceSchemaSha256: sha256(schemaText),
  desiredSqlSha256: sha256(desired),
  sources: sources.sources.map(({ path, repository, revision, sourcePath, sha256: digest }) => ({
    path,
    repository,
    revision,
    sourcePath,
    sha256: digest,
  })),
}, null, 2) + "\n";

await writeOrCheck("contracts/database/desired.sql", desired);
await writeOrCheck("generated/provenance.json", provenance);
